### ISSUE TITLE
Getting last timestamp for a given sensor

### ISSUE THREAD

**Issue by saroele** [flukso/tmpo-py#13]
I would like to have a method to get the last measurement timestamp for a given sensor.  Something like this:

```
tmpos = tmpo.Session()
tmpos.get_last_ts(sid) 
>> epoch 
```

Maybe something similar is already implemented but I can't find it.

**Comment by steel-finger** [comment]
You can use the tail function

**Comment by JrtPec** [comment]
@Jimmy-Dinis I think what @saroele means is a way to get the timestamp without having to unpack a lot of data.

I would also like a method to get the the first timestamp for a sensor.

**Comment by JrtPec** [comment]
Pull request in #16

**Comment by JrtPec** [comment]
Methods for the first and last timestamp have been added, so I guess this could be closed.

However, I think we can maybe refine the `last_timestamp` method:

Right now, it works by fetching the last available TMPO block by querying `SQL_TMPO_LAST`, after which it calls `_blocktail` on that block. `_blocktail` calculates the theoretical end point of that block, based on the block id and the level. The result is therefore approximate, not the exact last timestamp of the data.
@icarus75 Do you think there is an easy (and fast) way to pull the actual last timestamp from the last block?

**Comment by icarus75** [comment]
Why, yes there is! Each tmpo block contains a header with metadata, including the head and tail datapoints of the block. So we could return a (timestamp, value) tuple for the head and tail method. Example:
```javascript
{
"h":{
    "cfg": {"port":[3],"subtype":"pplus","id":"e12128a34d56bdd106541b8b71cd45b2","type":"electricity","data_type":"counter","rid":0},
    "tail":[1488977919,1464712.683],
    "vsn":1,
    "head":[1487929344,1058252.149]},
"t":[...],
"v":[...]
}
```
