### ISSUE TITLE
Elusive HTTP 500 Errors

### ISSUE THREAD

**Issue by JrtPec** [flukso/tmpo-py#18]
Sometimes I get a HTTP Error 500 when syncing my TMPO-database:
`HTTPError: 500 Server Error: Internal Server Error for url: https://api.flukso.net/sensor/53b1eb0479c83dee927fff10b0cb0fe6/tmpo/sync?lvl=8&rid=0&bid=1477928960`

It is quite hard to recreate these errors, I think because it has something to do with a faulty level-8 block, which gets overwritten after a while.

Note: Getting these HTTP-errors to raise requires a merge of #17, otherwise you will just get a JSONDecodeError which tells you nothing.

**Comment by icarus75** [comment]
A 500 error should contain a call trace of the offending code in the return body. Capturing these traces would help a lot in pinpointing the issue.

**Comment by icarus75** [comment]
Should be fixed with https://github.com/flukso/fls/commit/177dd095437f4439c3070d44900f9c51caba1e00. Re-open when you see a 500 or 597 in your error logs.
