### ISSUE TITLE
Question/Docu request: Please specify required additional modules beyond standard

### ISSUE THREAD

**Issue by gebhardm** [flukso/tmpo-py#3]
On trying the tmpo.py-example I instantly get an "ImportError: No module named requests_futures.sessions", so I should add "https://pypi.python.org/pypi/requests-futures" first? What additional assumptions does the tmpo import make beyond a standard Python 2.7 installation? Please add to the docu (as time is costly).
Thanks and regards
Markus

**Comment by icarus75** [comment]
Have a look at all the import statements in tmpo.py:
'''python
import os
import io
import math
import time
import sqlite3
import requests_futures.sessions
import concurrent.futures
import zlib
import re
import json
import numpy as np
import pandas as pd
'''

**Comment by gebhardm** [comment]
Well, this I have seen (as there is the code); nevertheless it would be nice to get a reference where to take non-standard libs from without extensive googling... (consumer convenience)

**Comment by gebhardm** [comment]
With the pip install this is actually is no issue any more...
