### ISSUE TITLE
HTTPError using Flukso Credentials

### ISSUE THREAD

**Issue by Jorisdehoog** [flukso/tmpo-py#41]
Hello, 

I'm trying out tmpo-py and when using the Flukso credentials my script throws the following exeption: 
`Exception has occurred: HTTPError
401 Client Error: Unauthorized for url: https://api.flukso.net/sensor/d9c7e8e07d05628ff407e0909e22cd34/tmpo/sync?rid=0&lvl=0&bid=0`

This happens in the following line:
```python
import tmpo
s = tmpo.Session()
s.debug = True
s.add("fed676021dacaaf6a12a8dda7685be34", "b371402dc767cc83e41bc294b63f9586") 
s.sync() #<-- HERE
```

The same issue when using a sensorID and token from my flukso counter. 
Thanks!

**Comment by icarus75** [comment]
Sync works fine on Python 3.5.2 with tmpo version 0.2.8. Try deleting the entry for `fed676021dacaaf6a12a8dda7685be34`:
```python
s.delete("fed676021dacaaf6a12a8dda7685be34")
```
Then re-run your code snippet.

**Comment by Jorisdehoog** [comment]
Well, upon further review I realised that the generated tmpo folder after `s = tmpo.Session()` needs to be in the same directory as my script. My `os.getcwd()` is situated one level above, so probably when syncing the certificate/DB is not found, as it resides also one level above. Anyway, when that's fixed it works!
