### ISSUE TITLE
List dependencies

### ISSUE THREAD

**Issue by saroele** [flukso/tmpo-py#8]
I'm running into a bug with pandas 0.13.1.  What is the minimum required pandas version? 

Here's the trace:

TypeError                                 Traceback (most recent call last)
<ipython-input-5-a6903dcad8ac> in <module>()
      2 sensors = hp.get_sensors_by_type('electricity')
      3 #sensors.remove('b325dbc1a0d62c99a50609e919b9ea06')
----> 4 dfcum = tmpos.dataframe(sids=sensors, head=start)
      5 print "Size of dataframe before resampling: {}".format(dfcum.shape)
      6 #print dfcum.head()

/usr/local/src/tmpo-py/tmpo.py in dataframe(self, sids, head, tail, datetime)
    217         tail = self._2epochs(tail)
    218         series = [self.series(sid, head=head, tail=tail, datetime=False)
--> 219                   for sid in sids]
    220         df = pd.concat(series, axis=1)
    221         if datetime is True:

/usr/local/src/tmpo-py/tmpo.py in series(self, sid, recycle_id, head, tail, datetime)
    203             and head < self._blocktail(lvl, bid)
    204             and tail >= bid):
--> 205                 srlist.append(self._blk2series(ext, blk, head, tail))
    206         if len(srlist) > 0:
    207             ts = pd.concat(srlist).truncate(before=head, after=tail)

/usr/local/src/tmpo-py/tmpo.py in _blk2series(self, ext, blk, head, tail)
    244             orient="split",
    245             numpy=True,
--> 246             date_unit="s")
    247         h = json.loads(m.group("h"))
    248         self._npdelta(pdsblk.index, h["head"][0])

TypeError: read_json() got an unexpected keyword argument 'date_unit'

**Comment by icarus75** [comment]
tmpo dependencies should be downloaded via egg spec by now
