### ISSUE TITLE
package 

### ISSUE THREAD

**Issue by saroele** [flukso/tmpo-py#9]
Would be great if tmpo-py would be packaged so we can install it with `pip install tmpo`

**Comment by icarus75** [comment]
True. I haven't yet packaged a lib for Python. Maybe Arnout can help us out?

**Comment by saroele** [comment]
He definitely can.  
We're doing it also at work.  I can check if I can 'borrow' the code.  Don't think it's that hard, but a good example will save us quite some time.

**Comment by icarus75** [comment]
Fixed with https://github.com/flukso/tmpo-py/pull/11. Pip install tmpo now does the job. Thanks Roel!
